### ISSUE TITLE
Debian targets use "smbd" and "nmbd" instead of "smb" and "nmb" for service names

### ISSUE THREAD

**Issue by chrisruffalo** [gluster/storhaug#13]
When attempting to use storhaug on Debian there are potential problems with the naming of the services because Debian targets use "smbd" and "nmbd" instead of "smb" and "nmb"

**Comment by kalebskeithley** [comment]
Nothing in storhaug tries to start smb or nmb (or smbd or nmbd) services. Not directly. 

If ctdb is configured to start SMB it's ctdb that will try to start it, but that's outside of anything in storhaug. And I presume the ctdb and /etc/ctdb/* files shipped on debian and ubuntu know and use the correct service names.

Is there something specific that storhaug has got wrong on debian? I would have guessed it might need `systemctl start ctdbd` instead of `systemctl start ctdb`. But no, the ctdb in my Ubuntu bionic box is just ctdb (/etc/init.d/ctdb) and systemctl will start it from the init.d/ctdb and doesn't recognize ctdbd as a service.

**Comment by chrisruffalo** [comment]
This is my fault, I got confused as to where I was. I was getting this project confused with https://github.com/linux-ha-storage/storhaug/tree/master/src which appears to do what I mentioned (https://github.com/linux-ha-storage/storhaug/blob/master/src/storhaug#L318-L323).  I wasn't aware of the exact relationship between the two repositories or what each one was for.

Thanks!

**Comment by kalebskeithley** [comment]
Yes, that's the old/original storhaug that was written using pacemaker. It's defunct AFAIC.

So I can close this issue?

**Comment by chrisruffalo** [comment]
Yes. Thank you.
